all: tp2-forcabruta tp2-pd

tp2-forcabruta: tp2-forcabruta.c
	gcc -g tp2-forcabruta.c -o tp2-forcabruta

#Talvex trocar por guloso depois, ver
tp2-pd: tp2-pd.c
	gcc -g tp2-pd.c -o tp2-pd

clean:
	rm tp2-forcabruta
	rm tp2-pd
