# Como adicionar uma nova PA resolvida:
### 1o) ADICIONAR O NUMERO DELA NA REGRA ALL NO INCIO
# all: <numPA1> <numPA2> <numPA3> <numPA4>
### 2o) ADICIONAR A REGRA DE COMPILACAO DELA
# <numPA>: <numPA>_ana_avelar.c
# gcc -g <numPA>_ana_avelar.c -o <numPA>
### 3o) ADICIONAR LINHA DELA NO CLEAN PARA LIMPAR
#	rm <numPA>

all: 1286

1286: 1286.c
	gcc -g 1286.c -o 1286

clean:
	rm 1286
