all: tp3

tp3: tp3.c
	gcc tp3.c -Wall -Wextra -Werror -std=c99

# Exemplo de inclusao de bibliotecas
#tp2-pd: tp2-pd.o pd.o
#	gcc pd.o tp2-pd.o -o tp2-pd

#tp2-pd.o: tp2-pd.c pd.h pd.c
#	gcc -g -c tp2-pd.c

#pd.o: pd.c pd.h
#	gcc -g -c pd.c

clean:
	rm *.o
	rm tp3
	# Mais do exemplo:
	#rm tp2-pd
